# SPDX-FileCopyrightText: Copyright (c) 2025-2026 Max Trunnikov
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: deps-sentinel
'on':
  schedule:
    - cron: '0 * * * *'
jobs:
  sentinel:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - uses: maxonfjvipon/deps-sentinel-action@0.0.4
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          owner: maxonfjvipon
