# SPDX-FileCopyrightText: Copyright (c) 2025-2026 Max Trunnikov
# SPDX-License-Identifier: MIT
---
name: mutation
'on':
  schedule:
    - cron: '0 2 * * 0'
  workflow_dispatch:
concurrency:
  group: mutation-${{ github.ref }}
  cancel-in-progress: true
jobs:
  mutation:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npx stryker run
  report-fail:
    name: Create issue on failure
    needs: mutation
    if: failure() && github.event.pull_request == null
    runs-on: ubuntu-24.04
    permissions:
      issues: write
    steps:
      - uses: jayqi/failed-build-issue-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          label-name: mutation failed
