# SPDX-FileCopyrightText: Copyright (c) 2025-2026 Max Trunnikov
# SPDX-License-Identifier: MIT
---
name: xcop
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  xcop:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - run: gem install xcop -v 0.11.0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npx mocha test/xcop.test.js --timeout 30000 --forbid-pending
      - run: >-
          xcop --license LICENSE.txt
          --include '**/*.xsl' --include '**/*.xml'
          --exclude 'test/resources/malformed/**'
          --exclude 'test/resources/fix/**'
          --exclude 'test/resources/directives/wrapped*.xsl'
